linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
      - name: var-naming
      - name: blank-imports
      - name: error-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: indent-error-flow

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
